/**
 * Base selector generation utilities
 * Shared across all selector generation strategies
 */

export const AUTO_GENERATED_PATTERNS = [
  /^framer-[a-zA-Z0-9]+$/,
  /^css-[a-z0-9]+$/i,
  /^sc-[a-zA-Z0-9]+$/,
  /^v-[a-f0-9]{8}$/,
  /^svelte-[a-z0-9]+$/,
  /^emotion-[0-9]+$/,
  /^chakra-[a-z]+__[a-z]+-[a-z0-9]+$/,
  /^MuiBox-root-[0-9]+$/,
  /^[a-f0-9]{8,}$/i,
  /_[a-f0-9]{6,}$/i,
  /^[a-zA-Z]+[0-9][a-zA-Z0-9]{15,}[_-]/,
  /^[a-zA-Z]+[0-9]{3,}[a-zA-Z]+[0-9]{3,}/
]

export const TEMPORARY_CLASSES = [
  'hover', 'active', 'focus', 'focused', 'selected', 'disabled',
  'loading', 'animating', 'transitioning', 'entering', 'leaving',
  'is-hovered', 'is-active', 'is-focused', 'is-selected',
  'framer-hover', 'framer-active', 'framer-v-hover'
]

export const SEMANTIC_PATTERNS = [
  /^(btn|button)/i,
  /^(nav|navigation)/i,
  /^(header|footer|main|sidebar)/i,
  /^(card|modal|dialog|dropdown)/i,
  /^(form|input|field)/i,
  /^(title|heading|text|content)/i,
  /^(primary|secondary|success|warning|error|info)/i,
  /^(large|medium|small|lg|md|sm|xs)/i,
  /^(container|wrapper|section|row|col)/i
]

export interface SelectorOptions {
  preferDataAttributes?: boolean
  includeParentContext?: boolean
  maxParentLevels?: number
  avoidAutoGenerated?: boolean
  debug?: boolean
}

export function escapeSelector(str: string): string {
  if (typeof CSS !== 'undefined' && CSS.escape) {
    return CSS.escape(str)
  }
  return str.replace(/([:#.\[\](),>+~"'=\s])/g, '\\$1')
}

export function isAutoGenerated(str: string): boolean {
  if (!str) return false

  if (str.includes('absmartly') || str.includes('ABSmartly')) {
    return true
  }

  if (/^[0-9]/.test(str)) {
    return true
  }

  return AUTO_GENERATED_PATTERNS.some(pattern => pattern.test(str))
}

export function isSemantic(className: string): boolean {
  return SEMANTIC_PATTERNS.some(pattern => pattern.test(className))
}

export function isTemporary(className: string): boolean {
  return TEMPORARY_CLASSES.includes(className.toLowerCase())
}

export function testSelectorUniqueness(selector: string, element: Element): boolean {
  try {
    const matches = document.querySelectorAll(selector)
    return matches.length === 1 && matches[0] === element
  } catch {
    return false
  }
}

export function getCleanClasses(element: Element): string[] {
  if (!element.className || typeof element.className !== 'string') {
    return []
  }

  return element.className
    .trim()
    .split(/\s+/)
    .filter(cls =>
      cls &&
      !cls.includes('absmartly') &&
      !isAutoGenerated(cls) &&
      !isTemporary(cls)
    )
}

export function getParentPath(element: Element, maxLevels: number = 3): Element[] {
  const path: Element[] = []
  let current = element.parentElement

  while (current && path.length < maxLevels) {
    path.push(current)
    current = current.parentElement
  }

  return path
}
