/**
 * Unified Selector Generator API
 * Consolidates multiple selector generation implementations
 */

import { generateCSSSelector } from './css-strategy'
import type { SelectorOptions } from './base'

export type { SelectorOptions } from './base'
export { generateCSSSelector } from './css-strategy'
export {
  isAutoGenerated,
  isSemantic,
  isTemporary,
  escapeSelector,
  testSelectorUniqueness,
  getCleanClasses
} from './base'

export function generateRobustSelector(
  element: Element,
  options: SelectorOptions = {}
): string {
  return generateCSSSelector(element, {
    preferDataAttributes: true,
    includeParentContext: true,
    maxParentLevels: 3,
    avoidAutoGenerated: true,
    ...options
  })
}

export default generateRobustSelector
